name: Build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: output
    build_type: ant
    script: |-
      #!/bin/bash
      ant
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: arpanroy@in.ibm.com
      space: genericbank
      application: BDSv1Sandbox
    script: |
      #!/bin/bash
      cf push "${CF_APP}"
- name: SeleniumStage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: stage
  jobs:
  - name: Test
    type: tester
    script: |-
      #!/bin/bash
      # invoke tests here
      ant unit-test-2
